services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ecommerce
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: